# Site settings
title: "[i]ooner"
email: hello@iooner.me
description: > # this means to ignore newlines until "baseurl:"
  iooner.me - DIY, Hack, Développement web, Domotique.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.iooner.me" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

timezone: Europe/London
encoding: utf-8
permalink: /:title/

paginate: 3
paginate_path: "blog/:num"

#image:
#  source: img/upload
#  output: img/upload
#  	presets:
#  		une:
#  			width: 740
#  			height: 175
#  			attr:
#        		class: img-full