# Site settings
title: "[i]ooner"
email: hello@iooner.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.iooner.me" # the base hostname & protocol for your site
twitter_username: iooner
github_username:  iooner

# Build settings
markdown: kramdown

timezone: Europe/Brussels
encoding: utf-8
permalink: /:title/

paginate: 3
paginate_path: "blog/:num"

#image:
#  source: img/upload
#  output: img/upload
#  	presets:
#  		une:
#  			width: 740
#  			height: 175
#  			attr:
#        		class: img-full